name: HENRY_CI_SECRET
on:
  push:
    branches: [main]
    workflow-dispatch:
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - docker login -u carsonehenry -pass mysupersecret
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.HENRY_CI_SECRETS }}
        run: |
          echo "$SUPER_SECRET"
